'use strict';
const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
const ROOT=path.join(__dirname,'..'),PORT=Number(process.env.REPLAY_SHARING_PORT)||8191,DATA=fs.mkdtempSync(path.join(ROOT,'data','replay-sharing-')),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const failures=[];function check(name,value,detail){console.log((value?'PASS':'FAIL')+'  '+name+(value||!detail?'':' :: '+detail));if(!value)failures.push(name);}
class Client{constructor(name){this.name=name;this.messages=[];this.waiters=[];}async open(){this.ws=new WebSocket('ws://127.0.0.1:'+PORT+'/ws');this.ws.onmessage=e=>{const m=JSON.parse(e.data);this.messages.push(m);this.waiters.splice(0).forEach(resolve=>resolve());};await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject;});return this;}send(type,payload){this.ws.send(JSON.stringify({type,payload}));}async wait(type,timeout=6000,predicate=()=>true){const end=Date.now()+timeout;while(Date.now()<end){const index=this.messages.findIndex(item=>item.type===type&&predicate(item));if(index>=0)return this.messages.splice(index,1)[0];await new Promise(resolve=>{this.waiters.push(resolve);setTimeout(resolve,25);});}throw new Error(this.name+' wait '+type+' '+JSON.stringify(this.messages.slice(-8)));}close(){try{this.ws&&this.ws.close();}catch{}}}
async function register(client,index){await client.open();client.send('register',{uid:'u_replay_share_'+index,pin:'ReplayPin'+index,name:client.name});const reg=await client.wait('registered');client.uid=reg.payload.uid;client.token=reg.payload.token;client.send('hello',{uid:client.uid,token:client.token,proto:2});await client.wait('hello_ack');}
async function main(){
  const server=spawn(process.execPath,[path.join(ROOT,'server','index.js')],{env:{...process.env,PORT:String(PORT),DATA_DIR:DATA,NODE_ENV:'test',REPLAY_PUBLIC_DELAY_MS:'600000',REPLAY_SHARE_TTL_MS:'3600000',REWARD_TEST_MIN_DURATION_MS:'0',REWARD_TEST_MIN_ACTIONS:'0',REWARD_TEST_MIN_UNIQUE_ACTIONS:'0',REWARD_TEST_MIN_PLAYER_ACTIONS:'0',SUPABASE_URL:'',SUPABASE_KEY:'',DEEPSEEK_KEY:''},stdio:['ignore','pipe','pipe']});let output='';server.stdout.on('data',data=>output+=data);server.stderr.on('data',data=>output+=data);
  const clients=[new Client('ReplayA'),new Client('ReplayB'),new Client('ReplayC')];
  try{
    for(let i=0;i<100&&!output.includes('已启动');i++)await sleep(50);if(!output.includes('已启动'))throw new Error('server start failed '+output);
    for(let i=0;i<clients.length;i++)await register(clients[i],i+1);const [a,b,c]=clients;
    a.send('create',{capacity:2,visibility:'public'});const room=(await a.wait('created')).room;b.send('join',{room});await b.wait('joined');a.send('select_game',{game:'gomoku'});await a.wait('room_update',6000,m=>m.payload&&m.payload.game==='gomoku');await b.wait('room_update',6000,m=>m.payload&&m.payload.game==='gomoku');b.send('ready',{ready:true});await a.wait('room_update',6000,m=>m.payload&&m.payload.canStart===true);a.send('start');const started=await a.wait('started');await b.wait('started');a.send('move',{r:7,c:7});b.send('move',{r:7,c:8});await sleep(80);const results=[{slot:0,coins:1,rank:1},{slot:1,coins:0,rank:2}];a.send('result',{matchId:started.matchId,game:'gomoku',results});b.send('result',{matchId:started.matchId,game:'gomoku',results});await a.wait('result_ok');await b.wait('result_ok');
    a.send('replay_list');const list=(await a.wait('replay_list')).payload.items||[],item=list[0];check('Replay：参与者列表包含版本化回放与分享权限',!!item&&item.version==='replay-v1.1'&&item.canShare===true&&item.publicAt>item.createdAt,JSON.stringify(item));
    c.send('replay_list');const outsiderList=(await c.wait('replay_list')).payload.items||[];check('Replay：公开房在延迟期不会进入非参与者列表',!outsiderList.some(entry=>entry.replayId===item.replayId));
    c.send('replay_get',{replayId:item.replayId});const denied=await c.wait('replay_error');check('Replay：延迟期原始 replayId 拒绝非参与者',denied.reason==='replay_forbidden',JSON.stringify(denied));
    a.send('replay_share',{replayId:item.replayId});const shared=await a.wait('replay_shared'),token=shared.payload&&shared.payload.shareToken;check('Replay：参与者可创建有时限随机分享令牌',/^shr_[A-Za-z0-9_-]{20,}$/.test(String(token||''))&&shared.payload.expiresAt>Date.now(),JSON.stringify(shared.payload));
    const dbText=fs.readFileSync(path.join(DATA,'leaderboard.json'),'utf8');check('Replay：持久化只保存分享令牌哈希',!dbText.includes(token)&&dbText.includes('shareTokenHash'));
    c.send('replay_get',{shareToken:token});const sharedReplay=await c.wait('replay_data');check('Replay：分享令牌可在权限边界内读取动作流',sharedReplay.payload.replayId===item.replayId&&sharedReplay.payload.moveLog.length>=2);
    a.send('replay_unshare',{replayId:item.replayId});await a.wait('replay_unshared');c.send('replay_get',{shareToken:token});const revoked=await c.wait('replay_error');check('Replay：撤销后旧分享令牌立即失效',revoked.reason==='replay_forbidden');
    if(!failures.length)console.log('REPLAY_SHARING_ALL_PASS');
  }finally{clients.forEach(client=>client.close());server.kill();try{fs.rmSync(DATA,{recursive:true,force:true});}catch{}}
  if(failures.length){console.error('REPLAY_SHARING_FAILED:',failures.join('、'));process.exitCode=1;}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
