'use strict';
const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),crypto=require('crypto');
const WebSocket=global.WebSocket||require('ws');
const ROOT=path.join(__dirname,'..'),SERVER=path.join(ROOT,'server','index.js');
const port=18000+Math.floor(Math.random()*1000),data=fs.mkdtempSync(path.join(ROOT,'data','seat-'));
let server,fail=0,log='';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function check(name,ok,detail){console.log((ok?'PASS ':'FAIL ')+name+(detail?' :: '+detail:''));if(!ok)fail++;}
class Client{
  constructor(name){this.name=name;this.messages=[];this.waiters=[];}
  async open(){this.ws=new WebSocket('ws://127.0.0.1:'+port+'/ws');this.ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}let consumed=false;this.waiters=[...this.waiters].filter(w=>{if(!consumed&&w.p(m)){consumed=true;w.r(m);return false}return true});if(!consumed)this.messages.push(m)};await new Promise((r,j)=>{this.ws.onopen=r;this.ws.onerror=j});return this;}
  send(type,payload){this.ws.send(JSON.stringify({type,payload}));}
  wait(predicate,label,timeout=4000){const found=this.messages.find(predicate);if(found){this.messages.splice(this.messages.indexOf(found),1);return Promise.resolve(found)}return new Promise((resolve,reject)=>{const t=setTimeout(()=>{this.waiters=this.waiters.filter(w=>w!==entry);reject(new Error(this.name+' timeout '+label))},timeout);const entry={p:predicate,r:m=>{clearTimeout(t);resolve(m)}};this.waiters.push(entry)})}
  async register(name){const uid='u_seat'+crypto.randomBytes(6).toString('hex'),pin='Seat'+crypto.randomBytes(5).toString('hex');this.send('register',{uid,pin,name,avatar:100});const m=await this.wait(x=>x.type==='registered','register');this.uid=m.payload.profile.uid;this.token=m.token||m.payload.token;this.messages=[];return this;}
  close(){try{this.ws.close()}catch{}}
}
async function main(){
  server=spawn(process.execPath,[SERVER],{env:{...process.env,PORT:String(port),DATA_DIR:data,NODE_ENV:'test',RECONNECT_GRACE_MS:'300',REWARD_TEST_MIN_DURATION_MS:'0',REWARD_TEST_MIN_ACTIONS:'0',REWARD_TEST_MIN_UNIQUE_ACTIONS:'0',REWARD_TEST_MIN_PLAYER_ACTIONS:'0',SUPABASE_URL:'',SUPABASE_KEY:''},stdio:['ignore','pipe','pipe']});server.stdout.on('data',d=>log+=d);server.stderr.on('data',d=>log+=d);await new Promise((resolve,reject)=>{const start=Date.now();const tick=()=>{require('http').get('http://127.0.0.1:'+port+'/',r=>{r.resume();if(r.statusCode===200)resolve();else setTimeout(tick,30)}).on('error',()=>Date.now()-start>5000?reject(new Error('server')):setTimeout(tick,30))};tick()});
  const host=await new Client('host').open(),human=await new Client('human').open(),spectator=await new Client('spectator').open(),attacker=await new Client('attacker').open();await Promise.all([host.register('房主'),human.register('真人'),spectator.register('观战者'),attacker.register('攻击者')]);
  host.send('create',{capacity:3,visibility:'public',allowSpectators:true});const created=await host.wait(x=>x.type==='created','created');const room=created.room;check('创建房间返回统一 Seat 协议',created.payload&&Array.isArray(created.payload.seats)&&created.payload.seats[0].type==='human');
  const hostSeat=await host.wait(x=>x.type==='room_update','host room');check('初始房间包含空席',hostSeat.payload.seats.some(s=>s.type==='empty'));
  const attackerMark=attacker.messages.length;attacker.send('add_ai',{difficulty:'hard',persona:'teacher'});await sleep(120);check('非房主不能添加 AI',attacker.messages.slice(attackerMark).every(m=>m.type!=='room_update'&&m.type!=='created'));
  host.send('add_ai',{difficulty:'hard',persona:'teacher'});const aiUpdate=await host.wait(x=>x.type==='room_update'&&x.payload.aiCount===1,'AI seat');const ai=aiUpdate.payload.seats.find(s=>s.type==='ai');check('AI 是真实服务端 Seat 且绑定 controllerUid',!!ai&&ai.controllerUid===host.uid&&ai.ready===true);
  host.send('room_settings',{visibility:'private'});await host.wait(x=>x.type==='room_update'&&x.payload.visibility==='private','private');attacker.send('lobby');const privateLobby=await attacker.wait(x=>x.type==='lobby','private lobby');check('私密房不出现在公开大厅',!privateLobby.payload.some(item=>item.room===room));
  host.send('room_settings',{visibility:'public'});await host.wait(x=>x.type==='room_update'&&x.payload.visibility==='public','public');human.send('quick_join',{});const quickJoined=await human.wait(x=>x.type==='joined','quick joined');check('快速加入进入符合条件的公开房',quickJoined.room===room);host.send('select_game',{game:'ludo'});await host.wait(x=>x.type==='room_update'&&x.payload.game==='ludo','game selected');human.send('ready',{ready:true});await host.wait(x=>x.type==='room_update'&&x.payload.canStart===true,'ready');
  spectator.send('spectate',{room});const watching=await spectator.wait(x=>x.type==='spectating','spectate');check('公开房可观战且观战者没有 player 席位',watching.payload.spectator===true&&watching.payload.player==null);
  host.send('start');const started=await host.wait(x=>x.type==='started','started');await human.wait(x=>x.type==='started','started human');await spectator.wait(x=>x.type==='started','started spectator');check('READY 后房主开始，观战者收到开局',started.seats.some(s=>s.type==='ai')===true);
  human.send('bot_move',{seatId:ai.seatId,payload:{dice:4}});const spoofReply=await human.wait(x=>x.type==='gameplay_error','spoof bot');check('非控制者不能伪造 bot_move',spoofReply.payload&&spoofReply.payload.reason==='unauthorized_or_inactive');
  const moveMark=human.messages.length;host.send('bot_move',{seatId:ai.seatId,payload:{dice:4}});const botMove=await human.wait(x=>x.type==='move'&&x.player===ai.seatId,'trusted bot move');check('房主托管 AI 以 AI Seat 身份广播走子',botMove.payload&&botMove.payload.dice===4&&botMove.player===ai.seatId);
  const before= spectator.messages.length;spectator.send('move',[1,1]);await sleep(100);check('观战者不能提交走子',spectator.messages.slice(before).every(m=>!(m.type==='move'&&Array.isArray(m.payload)&&m.payload[0]===1&&m.payload[1]===1)));
  host.send('move',{dice:2});human.send('move',{dice:3});await sleep(80);const results=[{slot:0,coins:1,rank:1},{slot:1,coins:0,rank:2},{slot:2,coins:0,rank:3}];host.send('result',{matchId:started.matchId,game:'ludo',results});human.send('result',{matchId:started.matchId,game:'ludo',results});const hostResult=await host.wait(x=>x.type==='result_ok','host result'),humanResult=await human.wait(x=>x.type==='result_ok','human result');check('混合房只向真人身份结算，AI 不成为奖励账号',hostResult.payload.reward.mode==='online'&&humanResult.payload.reward.mode==='online'&&!spectator.messages.some(x=>x.type==='result_ok'));
  const leaveMark=human.messages.length;host.send('leave');const hostChanged=await human.wait(x=>x.type==='host_changed','host transfer');check('房主主动离开后转移到下一真人',hostChanged.payload&&hostChanged.payload.uid===human.uid);const transferred=await human.wait(x=>x.type==='room_update'&&x.payload.host&&x.payload.host.uid===human.uid,'transferred room');const transferredAI=transferred.payload.seats.find(s=>s.type==='ai');check('房主转移后 AI controllerUid 同步接管',transferredAI&&transferredAI.controllerUid===human.uid);
  human.messages=human.messages.filter(x=>x.type!=='result_ok'&&x.type!=='started');human.send('start');const soloStarted=await human.wait(x=>x.type==='started','single human ai start');human.messages=human.messages.filter(x=>x.type!=='result_ok');human.send('move',{dice:5});human.send('result',{matchId:soloStarted.matchId,game:'ludo',results:[{slot:0,coins:0,rank:2},{slot:1,coins:1,rank:1}]});const soloResult=await human.wait(x=>x.type==='result_ok'&&x.matchId===soloStarted.matchId,'single human ai result');check('单真人 + AI 使用 AI 奖励模式与日上限',soloResult.payload.reward&&soloResult.payload.reward.mode==='ai',JSON.stringify(soloResult.payload.reward));
  human.send('end_game');await human.wait(x=>x.type==='end_game','end solo');host.send('join',{room});await host.wait(x=>x.type==='joined','old host rejoin');human.messages=[];host.messages=[];human.send('select_game',{game:'ludo'});await host.wait(x=>x.type==='room_update'&&x.payload.game==='ludo','select reconnect game');host.send('ready',{ready:true});await human.wait(x=>x.type==='room_update'&&x.payload.canStart===true&&x.payload.game==='ludo','reconnect ready');human.send('start');await host.wait(x=>x.type==='started'&&x.game==='ludo','reconnect started');human.send('debug_disconnect');await host.wait(x=>x.type==='peer_status'&&x.payload.online===false,'new host offline');await host.wait(x=>x.type==='host_changed'&&x.payload.uid===host.uid,'abnormal host transfer',3000);const abnormal=await host.wait(x=>x.type==='room_update'&&x.payload.host&&x.payload.host.uid===host.uid,'abnormal room',3000);check('房主异常断线超时后 AI 托管者同步转移',abnormal.payload.seats.find(s=>s.type==='ai').controllerUid===host.uid);
  [host,human,spectator,attacker].forEach(c=>c.close());
}
main().catch(e=>{console.error('ROOM_SEATS_CRASH',e.stack||e);fail++}).finally(async()=>{if(server&&server.exitCode===null)server.kill();await sleep(80);try{fs.rmSync(data,{recursive:true,force:true})}catch{}console.log(fail?'ROOM_SEATS_HAS_FAILURES':'ROOM_SEATS_ALL_PASS');process.exitCode=fail?1:0});
