'use strict';
const fs=require('fs'),path=require('path');const ROOT=path.join(__dirname,'..');let failures=0;const check=(name,ok)=>{console.log((ok?'PASS  ':'FAIL  ')+name);if(!ok)failures++;};
const modulePath=path.join(ROOT,'shared/progression/victory-mastery.js');const api=require(modulePath);
check('mastery module and catalog are frozen',Object.isFrozen(api)&&Object.isFrozen(api.CATALOG)&&api.CATALOG.length===30);
check('six games use exact 1/10/50/100/1000 thresholds',api.GAME_IDS.length===6&&api.GAME_IDS.every(game=>JSON.stringify(api.CATALOG.filter(item=>item.game===game).map(item=>item.threshold))===JSON.stringify([1,10,50,100,1000])));
const derived=api.deriveVictoryMastery({gomoku:0,ludo:1,monopoly:10,tank:50,tetris:100,xiangqi:1000,unknown:999999,__proto__:{polluted:true}});
check('threshold boundaries derive the expected current titles',derived.byGame.gomoku.current===null&&derived.byGame.ludo.current.threshold===1&&derived.byGame.monopoly.current.threshold===10&&derived.byGame.tank.current.threshold===50&&derived.byGame.tetris.current.threshold===100&&derived.byGame.xiangqi.current.threshold===1000);
check('next target and remaining wins are deterministic',derived.byGame.gomoku.nextThreshold===1&&derived.byGame.gomoku.remaining===1&&derived.byGame.monopoly.nextThreshold===50&&derived.byGame.monopoly.remaining===40&&derived.byGame.xiangqi.nextThreshold===null);
check('unknown games and unsafe counts cannot enter projection',Object.keys(derived.byGame).length===6&&!Object.prototype.hasOwnProperty.call(derived.byGame,'unknown')&&!({}).polluted);
const inherited=Object.create({gomoku:1000}),normalizedInherited=api.normalizeWins(inherited);
const normalizedUnsafe=api.normalizeWins({ludo:-5,monopoly:10.9,tank:1e30,tetris:Symbol('bad'),xiangqi:Infinity});
check('only own wins count and inherited game fields are ignored',normalizedInherited.gomoku===0);
check('negative, fractional, huge and uncoercible counts normalize safely',normalizedUnsafe.ludo===0&&normalizedUnsafe.monopoly===10&&normalizedUnsafe.tank===1000000000&&normalizedUnsafe.tetris===0&&normalizedUnsafe.xiangqi===0);
check('projection is read-only and contains no economy fields',Object.isFrozen(derived)&&Object.isFrozen(derived.byGame)&&Object.isFrozen(derived.byGame.gomoku)&&!/(coins|xp|reward|price|owned)/i.test(JSON.stringify(derived)));
const server=fs.readFileSync(path.join(ROOT,'server/index.js'),'utf8'),build=fs.readFileSync(path.join(ROOT,'scripts/build.js'),'utf8'),shell=fs.readFileSync(path.join(ROOT,'public/src/core/02-app-shell.js'),'utf8');
check('server profile derives mastery from authoritative wins',/deriveVictoryMastery\(u\.wins\)/.test(server));
const editable=(server.match(/function updateEditableProfile\(u, payload\)\{([\s\S]*?)\n\}/)||[])[1]||'';
check('editable profile whitelist cannot write wins or mastery',editable&&!/u\.(wins|totalWins|mastery)\s*=/.test(editable)&&!/payload\.(wins|totalWins|mastery)/.test(editable));
check('browser build loads shared mastery before profile consumer',build.indexOf("../../shared/progression/victory-mastery.js")>=0&&build.indexOf("../../shared/progression/victory-mastery.js")<build.indexOf("core/02-app-shell.js"));
check('profile game cards consume server-projected mastery without mutation',/account\.mastery/.test(shell)&&/profile-game-mastery/.test(shell)&&!/mastery\s*=\s*payload/.test(shell));
if(failures){console.error('VICTORY_MASTERY_FAILURES='+failures);process.exitCode=1;}else console.log('VICTORY_MASTERY_ALL_PASS');
